### ISSUE TITLE
How to moved an issue that is linked to the PR

### ISSUE THREAD

**Issue by lukasz-madon** [peter-evans/create-or-update-project-card#113]
I'd like to move an issue card that is linked to the PR, but I'm not sure how to get linked issues

```
name: Move issues to project columns

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move issues to Code Review
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-location: 'myorg'
          project-name: 'project1'
          column-name: 'Code Review'
          issue-number: 29. # how to get a linked issue?
          token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pull_request' && github.event.action == 'opened'

      - name: Move issues to DEV
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-location: 'myorg'
          project-name: 'project1'
          column-name: 'DEV'
          issue-number: 29
          token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true


```
